{{- if .Values.roleBinding.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mychart.fullname" . }}-rb
subjects:
  - kind: ServiceAccount
    name: {{ include "mychart.fullname" . }}-sa
roleRef:
  kind: Role
  name: {{ include "mychart.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
